# Generated by Django 4.1.2 on 2023-07-10 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcafeteria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fotografia',
            field=models.ImageField(default='default.jpg', upload_to='Septima'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(max_length=40),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
